#!/usr/bin/env python3
"""
Calibrate nanotyper's QC thresholds against a finished project folder.

USAGE
    tools/qc_calibration.py <project_dir> [--out docs/qc-calibration.md]

    <project_dir> is a nanotyper project (see README "Recommended project
    layout"): it must contain analyses/<run>/results/ with per-sample BLAST
    tables, coverage TSVs and a combined summary, i.e. the output of
    batch_run.sh.

WHAT IT REPORTS
    1. Per-locus share of on-target reads  — which locus starves the sample and
       therefore caps its QC label regardless of sequencing depth.
    2. Allele-call quality vs per-locus depth — the fraction of locus calls that
       miss a known allele (`new_allele`), binned by both-primer coverage. This
       is what a coverage threshold is actually buying.
    3. The same, split by basecalling model family, because reads polished with
       a medaka model for another chemistry carry motif-specific errors that
       look like novel alleles.
    4. Recurrent single-mismatch positions — a hallmark of systematic basecall
       error rather than genuine novel alleles.
    5. Label counts under candidate (coverage_good, coverage_warn) rules.

Read-only: it never writes into the project folder.
"""
from __future__ import annotations

import argparse
import collections
import csv
import glob
import statistics
import sys
from pathlib import Path

LOCI_DEFAULT = ["adk", "fumC", "gyrB", "icd", "mdh", "purA", "recA"]
BLAST_COLS = ["qseqid", "sseqid", "pident", "length", "mismatch", "gapopen",
              "qstart", "qend", "sstart", "send", "evalue", "bitscore", "qlen", "slen"]
BINS = [(0, 10), (10, 20), (20, 30), (30, 50), (50, 100), (100, 200), (200, float("inf"))]
CANDIDATES = [(100, 50), (100, 20), (50, 20), (30, 15), (20, 10)]


def bin_label(b):
    lo, hi = b
    return f"{lo}-{'inf' if hi == float('inf') else int(hi)}"


def read_summary(project: Path, exclude=()):
    rows = []
    for p in sorted(project.glob("analyses/*/results/mlst_summary.tsv")):
        run = p.parent.parent.name
        if run in exclude:
            continue
        for r in csv.DictReader(open(p), delimiter="\t"):
            r["_run"] = run
            rows.append(r)
    return rows


def num(r, key):
    try:
        return float(r.get(key) or 0)
    except ValueError:
        return 0.0


def basecall_models(project: Path):
    """{(run, sample_id or barcode): model} — from results/, else the raw FASTQ headers.

    Keyed by both sample_id and barcode because the two differ: the summary rows
    carry sample_id, while the raw-data folders are named by barcode.
    """
    import gzip
    out = {}
    for p in project.glob("analyses/*/results/*/medaka/basecall_model.txt"):
        out[(p.parents[3].name, p.parents[1].name)] = p.read_text().strip() or "unknown"
    for d in project.glob("data/*/fastq_pass/*"):
        run = d.parents[1].name
        files = sorted(d.glob("*.fastq.gz"))
        if not files:
            continue
        try:
            with gzip.open(files[0], "rt") as fh:
                head = fh.readline()
        except OSError:
            continue
        model = "unknown"
        for tok in head.split():
            if tok.startswith("basecall_model_version_id="):
                model = tok.split("=", 1)[1]
        out.setdefault((run, d.name), model)
    return out


def model_for(models, run, sample_id, barcode):
    return models.get((run, sample_id)) or models.get((run, barcode)) or "unknown"


def family(model: str) -> str:
    m = (model or "").lower()
    for fam in ("r1041", "r10.4.1", "r104", "r10.4", "r941", "r9.4.1"):
        if fam in m:
            return fam.replace(".", "")
    return "unknown"


def section(title):
    return f"\n## {title}\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("project", type=Path)
    ap.add_argument("--out", type=Path, default=None, help="write Markdown here (default: stdout)")
    ap.add_argument("--loci", default=",".join(LOCI_DEFAULT))
    ap.add_argument("--exclude", default="",
                    help="comma-separated analysis folders to skip (e.g. scratch or demo runs)")
    a = ap.parse_args()
    loci = a.loci.split(",")

    excluded = {x for x in a.exclude.split(",") if x}
    rows = read_summary(a.project, excluded)
    if not rows:
        sys.exit(f"ERROR: no analyses/*/results/mlst_summary.tsv under {a.project}")
    models = basecall_models(a.project)
    out = [f"# QC calibration — `{a.project.name}`", "",
           f"{len(rows)} samples from {len({r['_run'] for r in rows})} runs"
           + (f" (excluded: {', '.join(sorted(excluded))})" if excluded else "")
           + ". Generated by `tools/qc_calibration.py` (read-only)."]

    # --- 1. locus share -------------------------------------------------
    shares = collections.defaultdict(list)
    for r in rows:
        cov = {l: num(r, f"{l}_coverage") for l in loci}
        tot = sum(cov.values())
        if tot <= 0:
            continue
        for l in loci:
            shares[l].append(100 * cov[l] / tot)
    out += [section("1. Share of on-target reads per locus"),
            "A locus with a small share caps the whole sample: at share *s* %, a barcode needs",
            "roughly `coverage_good / (s/100)` on-target reads before that locus clears the threshold.",
            "", "| locus | median % | p10 | p90 | reads needed for 100× |", "|---|---|---|---|---|"]
    for l in loci:
        v = sorted(shares[l])
        if not v:
            continue
        med = statistics.median(v)
        need = f"{round(100 / (med / 100), -2):,.0f}" if med > 0 else "—"
        out.append(f"| {l} | {med:.1f} | {v[len(v)//10]:.1f} | {v[9*len(v)//10]:.1f} | {need} |")

    # --- 2/3. call quality vs depth, overall and by model family --------
    def quality_table(subset, label):
        tot = collections.Counter()
        na = collections.Counter()
        for r in subset:
            for l in loci:
                c = num(r, f"{l}_coverage")
                for b in BINS:
                    if b[0] <= c < b[1]:
                        tot[b] += 1
                        na[b] += r.get(f"{l}_flag") == "new_allele"
                        break
        lines = [f"\n**{label}** ({len(subset)} samples)", "",
                 "| both-primer coverage | locus calls | `new_allele` % |", "|---|---|---|"]
        for b in BINS:
            if tot[b]:
                lines.append(f"| {bin_label(b)}× | {tot[b]} | {100*na[b]/tot[b]:.1f} |")
        return lines

    out += [section("2. Allele-call quality vs per-locus depth")]
    out += quality_table(rows, "All runs")
    by_fam = collections.defaultdict(list)
    for r in rows:
        by_fam[family(model_for(models, r["_run"], r["sample_id"], r.get("barcode", "")))].append(r)
    if len(by_fam) > 1:
        out += [section("3. The same, split by basecalling model family"),
                "Reads polished with a medaka model for a different chemistry keep motif-specific",
                "errors that BLAST reports as imperfect matches."]
        for fam, sub in sorted(by_fam.items(), key=lambda kv: -len(kv[1])):
            out += quality_table(sub, f"basecall model family: {fam}")

    # --- 4. recurrent mismatch positions --------------------------------
    hot = collections.Counter()
    for f in glob.glob(str(a.project / "analyses/*/results/*/blast/*_*.tsv")):
        locus = f.rsplit("_", 1)[1][:-4]
        if locus not in loci:
            continue
        best = None
        for r in csv.DictReader(open(f), delimiter="\t", fieldnames=BLAST_COLS):
            if best is None or float(r["bitscore"]) > float(best["bitscore"]):
                best = r
        if best and int(best["mismatch"]) == 1 and int(best["gapopen"]) == 0 \
                and int(best["length"]) == int(best["slen"]):
            hot[(locus, int(best["sstart"]))] += 1
    if hot:
        out += [section("4. Recurrent single-mismatch positions"),
                "A handful of positions accounting for many samples indicates systematic basecall",
                "error, not novel alleles.", "",
                "| locus | subject start | samples |", "|---|---|---|"]
        for (l, pos), n in hot.most_common(10):
            out.append(f"| {l} | {pos} | {n} |")

    # --- 5. candidate rules ---------------------------------------------
    def relabel(r, good, warn):
        flags = {l: r.get(f"{l}_flag") for l in loci}
        cov = {l: num(r, f"{l}_coverage") for l in loci}
        if any(f == "no_hit" for f in flags.values()) or min(cov.values()) < warn:
            return "FAIL"
        if min(cov.values()) < good:
            return "LOW_COVERAGE"
        if any(f == "new_allele" for f in flags.values()):
            return "NEW_ALLELE"
        if r.get("ST") == "new_ST":
            return "NEW_ST"
        return "PASS"

    out += [section("5. Label counts under candidate thresholds"), "",
            "| coverage_good | coverage_warn | PASS | NEW_ST | NEW_ALLELE | LOW_COVERAGE | FAIL |",
            "|---|---|---|---|---|---|---|"]
    for good, warn in CANDIDATES:
        c = collections.Counter(relabel(r, good, warn) for r in rows)
        out.append(f"| {good} | {warn} | " + " | ".join(str(c[k]) for k in
                   ["PASS", "NEW_ST", "NEW_ALLELE", "LOW_COVERAGE", "FAIL"]) + " |")

    text = "\n".join(out) + "\n"
    if a.out:
        a.out.parent.mkdir(parents=True, exist_ok=True)
        a.out.write_text(text)
        print(f"wrote {a.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
